name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract tag name
        shell: bash
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        id: tag_branch

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_DZD_USERNAME }}/${{ github.event.repository.name }}:${{ steps.tag_branch.outputs.tag }} -t ${{ secrets.DOCKERHUB_DZD_USERNAME }}/${{ github.event.repository.name }}:${{ github.event.release.target_commitish }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_DZD_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DZD_PASSWORD }}

      - name: Push docker image to dockerhub
        shell: bash
        run: docker push ${{ secrets.DOCKERHUB_DZD_USERNAME }}/${{ github.event.repository.name }} --all-tags
